Update build script

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# exit on error
+set -o errexit
+
 # Install dependencies
 pip install -r requirements.txt
 
@@ -7,11 +10,10 @@ pip install -r requirements.txt
 python manage.py collectstatic --no-input
 
 # Run migrations
-python manage.py makemigrations
 python manage.py migrate
 
 # Populate database
-if [[ $POPULATE_DB ]];
-then
-  python manage.py shell < bin/create_links.py
-fi
+# if [[ $POPULATE_DB ]];
+# then
+#   python manage.py shell < bin/create_links.py
+# fi
